### ISSUE TITLE
Gradle upgrade to v 2.12

### ISSUE THREAD

**Issue by itissid** [ysb33r/gnumake-gradle-plugin#5] opened 2016-04-06 22:37 UTC
Hi are you planning to release a version pegged to gradle v 2.12 anytime soon? I have tried using this plugin with 2.12 and get some NoSuchMethodErrors for certain methods like `targets`

**Comment by ysb33r** [comment] 2016-04-08 08:58
I'll do a fix for that as soon as I can.

**Comment by ysb33r** [comment] 2016-04-08 09:02
Can you paste a relevant of the stacktrace & error you are seeing?

**Comment by itissid** [comment] 2016-04-12 15:09
https://gist.github.com/itissid/949ebe4f4740dcc2e12e947be2f34810

**Comment by ysb33r** [comment] 2016-04-13 21:00
Can you just paste the line how you call `target`.

I suspect it might be relates to an API change, but I cannot reproduce it and I have tested it with pretty much all version from 2.1 - 2.12.

**Comment by itissid** [comment] 2016-04-18 22:58
Ah i think there was some missing info in my first message, I think by `target` I mean "gradle make target" I call it using `./gradlew --stacktrace makeClean` I included it in the first line of the gist.

**Comment by itissid** [comment] 2016-04-18 23:00
Its interesting it did not reproduce it for you. Is it possible there is conflict of API with some other plugin and that is causing the exception? I have only the shadow jar plugin https://github.com/johnrengelman/shadow additionally

**Comment by zimy** [comment] 2016-07-13 16:13
I am also affected. My build.gradle file:

```
plugins {
  id 'org.ysb33r.gnumake' version '1.0'
}

make {
  makefile 'Makefile'
  targets 'all', 'build'
}
```

And when calling with 

```
gradle -version
Gradle 2.12
Build time:   2016-03-17 15:59:54 UTC
Build number: Fedora 2.12-1.fc24
Revision:     <unknown>
Groovy:       2.4.5
Ant:          Apache Ant(TM) version 1.9.6 compiled on February 3 2016
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Linux 4.6.3-300.fc24.x86_64 amd64
```

```
gradle make --stacktrace
```

the following is produced:

```
[user@computer dir]$ gradle make --stacktrace
:make

FAILURE: Build failed with an exception.

* What went wrong:
org.gradle.util.CollectionUtils.stringize(Ljava/util/List;)Ljava/util/List;

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.NoSuchMethodError: org.gradle.util.CollectionUtils.stringize(Ljava/util/List;)Ljava/util/List;
    at org.ysb33r.gradle.gnumake.GnuMakeBuild.getTargets(GnuMakeBuild.groovy:101)
    at org.ysb33r.gradle.gnumake.GnuMakeBuild_Decorated.getTargets(Unknown Source)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)

```

**Comment by ysb33r** [comment] 2016-07-13 16:39
| java.lang.NoSuchMethodError: org.gradle.util.CollectionUtils.stringize(Ljava/util/List;)Ljava/util/List;

Ah, I know what that is. I'll try to get an update out by the end of this weekend.

**Comment by ysb33r** [comment] 2016-07-13 23:30
It looks like the commit might have fixed it on the `dev_1_1` branch. If you need this urgently you can trying cloning the branch and building yourself a SNAPSHOT. Otherwise I am just going to clean some stuff up first before pushing out the new release.

**Comment by ysb33r** [comment] 2016-07-14 17:47
This should be fixed now. The versions that were tested against are listed here:

  https://github.com/ysb33r/gnumake-gradle-plugin/blob/master/build.gradle#L73

I have pushed 1.1 to the plugin portal and will close this issue. If you find any issues with the release feel free to re-open it.

**Closed as completed by ysb33r** 2016-07-14 17:47 UTC
Labels: bug

**Comment by itissid** [comment] 2016-07-15 14:28
Cool thanks!
